# Generated by Django 2.2.13 on 2020-12-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=5000)),
                ('body', models.CharField(max_length=500000)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.postId')),
            ],
            options={
                'verbose_name': 'Comments',
            },
        ),
    ]
